// app/utils/schemas/datasetLoader.ts
import 'server-only';
import fs from 'fs';
import path from 'path';

/**
 * Load enhanced dataset file generated by generate-datasets.ts
 * 
 * These files contain:
 * - Enhanced variableMeasured (20+ items)
 * - Citation array (3+ items)
 * - Author E-E-A-T data (credentials, expertise, affiliation)
 * - Image references (hero + micro images with descriptions)
 * - Distribution array (JSON, CSV, TXT formats)
 * 
 * @param slug - Material/contaminant slug (e.g., "aluminum-laser-cleaning")
 * @param type - Dataset type ("materials" or "contaminants")
 * @returns Enhanced dataset data or null if file doesn't exist
 */
export function loadGeneratedDataset(slug: string, type: 'materials' | 'contaminants' = 'materials'): any | null {
  try {
    // Construct filename: materials use full slug, contaminants remove -contamination suffix
    // Materials: ${slug}-material-dataset.json (e.g., aluminum-laser-cleaning-material-dataset.json)
    // Contaminants: ${id}-contaminant-dataset.json (e.g., adhesive-residue-contaminant-dataset.json)
    const filename = type === 'materials' 
      ? `${slug}-material-dataset.json`
      : `${slug.replace('-contamination', '')}-contaminant-dataset.json`;
    const datasetPath = path.join(process.cwd(), 'public', 'datasets', type, filename);
    
    if (!fs.existsSync(datasetPath)) {
      console.warn(`📊 Generated dataset not found: ${datasetPath}`);
      return null;
    }
    
    const fileContent = fs.readFileSync(datasetPath, 'utf-8');
    const dataset = JSON.parse(fileContent);
    
    return dataset;
  } catch (error) {
    console.error(`Error loading generated dataset for ${slug}:`, error);
    return null;
  }
}

/**
 * Extract enhanced fields from generated dataset
 * 
 * @param dataset - Loaded dataset from loadGeneratedDataset()
 * @returns Object with enhanced fields for schema generation
 */
export function extractEnhancedFields(dataset: any) {
  if (!dataset) return null;
  
  return {
    variableMeasured: dataset.variableMeasured || [],
    citation: dataset.citation || [],
    creator: dataset.creator || null,
    author: dataset.author || null,
    image: dataset.image || null,
    distribution: dataset.distribution || [],
    license: dataset.license || null,
    publisher: dataset.publisher || null,
    keywords: dataset.keywords || [],
    measurementTechnique: dataset.measurementTechnique || null,
    includedInDataCatalog: dataset.includedInDataCatalog || null,
    dataQuality: dataset.dataQuality || null
  };
}
