// app/utils/schemas/datasetLoader.ts
import 'server-only';
import fs from 'fs';
import { getDatasetPath, getDatasetFilename } from '@/app/utils/slugHelpers';

/**
 * Load enhanced dataset file generated by generate-datasets.ts
 * 
 * These files contain:
 * - Enhanced variableMeasured (20+ items)
 * - Citation array (3+ items)
 * - Author E-E-A-T data (credentials, expertise, affiliation)
 * - Image references (hero + micro images with descriptions)
 * - Distribution array (JSON, CSV, TXT formats)
 * 
 * @param slug - BASE material/contaminant slug (e.g., "aluminum", NOT "aluminum-laser-cleaning")
 *               The slug should NOT include suffixes - they are added automatically
 * @param type - Dataset type ("materials" or "contaminants")
 * @returns Enhanced dataset data or null if file doesn't exist
 */
export function loadGeneratedDataset(slug: string, type: 'materials' | 'contaminants' = 'materials'): any | null {
  try {
    // Use shared utility for consistent path construction
    // This prevents duplicate suffix bugs
    const datasetPath = getDatasetPath(slug, type, 'json');
    const filename = getDatasetFilename(slug, type, 'json');
    
    if (!fs.existsSync(datasetPath)) {
      console.warn(`📊 Generated dataset not found: ${datasetPath}`);
      return null;
    }
    
    const fileContent = fs.readFileSync(datasetPath, 'utf-8');
    const dataset = JSON.parse(fileContent);
    
    return dataset;
  } catch (error) {
    console.error(`Error loading generated dataset for ${slug}:`, error);
    return null;
  }
}

/**
 * Extract enhanced fields from generated dataset
 * 
 * @param dataset - Loaded dataset from loadGeneratedDataset()
 * @returns Object with enhanced fields for schema generation
 */
export function extractEnhancedFields(dataset: any) {
  if (!dataset) return null;
  
  return {
    variableMeasured: dataset.variableMeasured || [],
    citation: dataset.citation || [],
    creator: dataset.creator || null,
    author: dataset.author || null,
    image: dataset.image || null,
    distribution: dataset.distribution || [],
    license: dataset.license || null,
    publisher: dataset.publisher || null,
    keywords: dataset.keywords || [],
    measurementTechnique: dataset.measurementTechnique || null,
    includedInDataCatalog: dataset.includedInDataCatalog || null,
    dataQuality: dataset.dataQuality || null
  };
}
